### ISSUE TITLE
Error when boost up with newest experiment build

### ISSUE THREAD

**Issue by Naadn** [Computer-Engineer-Man/cdda-mana-cores#3]
DEBUG    : error setting double destination in 'name: impurities', 'u_val: vitamin', 

 FUNCTION : static void kwargs_shim::throw_error(std::string_view)
 FILE     : src/math_parser_shim.h
 LINE     : 53
 VERSION  : b3a2e0d

and
 
 DEBUG    : unrecognized number source in 'name: impurities', 'u_val: vitamin', 

 FUNCTION : static void kwargs_shim::throw_error(std::string_view)
 FILE     : src/math_parser_shim.h
 LINE     : 53
 VERSION  : b3a2e0d

And when I trying to crack the core deliberately, the game crashed. Maybe is due to this update : https://github.com/CleverRaven/Cataclysm-DDA/pull/70996

Edit : I have fix the eoc.json myself by replace all the `u_val('vitamin', 'name: impurities')` with `u_vitamin('impurities')` , because I can't make PR so I attach the fixed file here. 
[eoc.json](https://github.com/Computer-Engineer-Man/cdda-mana-cores/files/14087237/eoc.json)

**Comment by Computer-Engineer-Man** [comment]
Closed with #4
