### ISSUE TITLE
Error regarding mana_multiplier

### ISSUE THREAD

**Issue by m0shmall0w** [Computer-Engineer-Man/cdda-mana-cores#7]
I get this error when i try to load the game. It doesnt stop me from playing but i believe it stops the mana multiplication from working

DEBUG    : (json-error)
Json error: C:/Users/gamer/OneDrive/Documents/Catapult CDDA/dda/userdata/mods/Mana-Cores/traits.json:12:21: <color_white><color_cyan>Invalid or misplaced field name "mana_multiplier" in JSON data</color>

		"player_display": true,
		"active": true,
<color_light_red>		"mana_multiplier": 1,
</color>
               <color_cyan>▲▲▲</color>
		"enchantments": [ "MANACORE1_BUFF" ],
		"spells_learned": [ [ "generate_mana", 1 ] ],
</color>

 FUNCTION : error_skipped_members
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\flexbuffer_json.cpp
 LINE     : 347
 VERSION  : 449edb2
****

**Comment by rty275** [comment]
I've got a PR open that fixes this, no idea when/if it'll be merged but you can steal the files from that and it'll work just fine.
